[general]
live_config_reload = true
import = [ "/home/tebby24/.config/alacritty/themes/tokyo-night.toml" ]

[window]
padding.x = 4 
dynamic_padding = true
opacity = 0.95

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
